name: cntk-py36
channels:
- defaults
# For imageio and dlib:
- conda-forge
dependencies:
- h5py
- jupyter
- matplotlib
- numpy==1.11.3
- opencv
- pandas
# Downgrade to 0.5.0 due to https://github.com/pydata/pandas-datareader/issues/495
- pandas-datareader==0.5.0
- pandoc
- pip
- python==3.6.5
- pyyaml
- scipy
- seaborn
- setuptools
- six
- wheel
- cython
- dlib
- pip:
  - easydict
  - gym[atari]
  - keras==2.0.6
  - pydot-ng
  - pygame
  - pytest==3.6.2
  - sphinx-rtd-theme
  - sphinx
  - nbsphinx
  - twine
  - protobuf==3.5.2
  - pillow
  - imageio
  - scikit-image
  - scikit-learn
